version: '3'
services:
  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres